channels:
  - defaults
dependencies:
  - python=3.9
  - anaconda::conda-build
  - anaconda::conda-verify
  - anaconda::sphinx
  - conda-forge::shapely
  - conda-forge::xmlrunner
  - esri::arcgis
