channels:
  - defaults
dependencies:
  - python=3.13
  - anaconda::libarchive
  - anaconda::libmamba
  - anaconda::conda-build
  - anaconda::conda-verify
  - anaconda::sphinx
  - conda-forge::shapely
